### ISSUE TITLE
API Explorer throws exception on invalid templates

### ISSUE THREAD

**Issue by davidkeaveny** [mulesoft-labs/raml-dotnet-apiexplorer#2]
If attribute routing is used, and the routing template references an action parameter that does not exist,  a null reference exception is thrown from the GetQueryParameters method:

```
System.NullReferenceException was unhandled by user code
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=RAML.WebApiExplorer
  StackTrace:
       at RAML.WebApiExplorer.ApiExplorerService.GetQueryParameters(IEnumerable`1 parameterDescriptions)
       at RAML.WebApiExplorer.ApiExplorerService.GetMethods(ApiDescription api, ICollection`1 verbs)
       at RAML.WebApiExplorer.ApiExplorerService.GetRaml(RamlVersion ramlVersion, String title)
       at RAML.WebApiExplorer.RamlController.GetRamlContents(String version) in d:\Dev\WebAPI\trunk\WebAPI\Controllers\RamlController.cs:line 41
       at RAML.WebApiExplorer.RamlController.Raw(String version) in d:\Dev\WebAPI\trunk\WebAPI\Controllers\RamlController.cs:line 17
       at lambda_method(Closure , ControllerBase , Object[] )
       at System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters)
       at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
       at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
       at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
       at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
       at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()
       at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
       at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
       at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
```

The exception should be handled, either by logging the error (to a trace?) and discarding the invalid action, or by rethrowing a more meaningful exception that would help the API developer track down the source of the error.

**Comment by woodp** [comment]
thanks for the feedback
handle of this case will be included in next release
